/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:a77392e5-3135-4af5-830e-dbf382f717e3",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_aoMUfOKII",
    "aws_user_pools_web_client_id": "2hlg83mti19ckh3jt56a826qft",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://rcnpsv2ft5dbje6fz2dcx6s3ke.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-zeixio32bjhsjiloxnm3ohcrhy",
    "aws_user_files_s3_bucket": "demobucket134313-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
